name: Publish the Signalling Server container image for Unreal Engine 5.1

on:
  push:
    branches: ['UE5.1']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  signalling-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push the Signalling Server container image for Unreal Engine 5.1
        uses: docker/build-push-action@v3
        with:
          context: ./SignallingWebServer
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
  pull-and-run:
    runs-on: self-hosted
    needs: signalling-server-image
    steps:
    -
        name: Pull and run Signalling Server container image for Unreal Engine 5.1
        run: docker pull ${{ env.REGISTRY }}/proun-movemenet/${{ env.IMAGE_NAME }}
  
