name: Publish the Signalling Server container image from our dev branch

on:
  push:
    branches: ['UE5.2']
    paths: ['SignallingWebServer/**']

jobs:
  signalling-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/proun-movemenet/${{ env.IMAGE_NAME }}
      - name: Build and push the Signalling Server container image for Unreal Engine based on our development branch 5.2
        uses: docker/build-push-action@v3
        with:
          context: ./SignallingWebServer
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
      - name: Extract metadata (tags, labels) for Docker
        id: meta_matchmaker
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/proun-movemenet/matchmaker
      - name: Build and push the Mathcmaker container image for Unreal Engine 5.2
        uses: docker/build-push-action@v3
        with:
          context: ./Matchmaker
          tags: ${{ steps.meta_matchmaker.outputs.tags }}
          labels: ${{ steps.meta_matchmaker.outputs.labels }}
          push: true
