name: Publish the Signalling Server container image for Unreal Engine 5.1

on:
  push:
    branches: ['UE5.1']
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  signalling-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Echo step
        run: echo ${{ github.actor }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR }}
      -
        name: Build and push the Signalling Server container image for Unreal Engine 5.1
        uses: docker/build-push-action@v3
        with:
          context: ./SignallingWebServer
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
